#include <windows.h>
#include <windowsx.h>
#include <commctrl.h>
#include <shellapi.h>
#include <dwmapi.h>
#include <psapi.h>
#include <mmsystem.h>
#include <wtsapi32.h>
#include <oleacc.h>
#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <filesystem>
#include <map>
#include <random>
#include <string>
#include <vector>
#include "resource.h"
#include "image.h"
#include "storage.h"
#include "obs.h"

using Clock=std::chrono::steady_clock;
static constexpr UINT WM_TRAY=WM_APP+1, WM_DESKTOP_CALL=WM_APP+2;
static constexpr UINT_PTR TIMER_TICK=1;
enum ControlId { ID_SIZE=2001,ID_OBSSIZE,ID_ACTIVITY,ID_COINMIN,ID_COINMAX,ID_SPEECHMIN,ID_SPEECHMAX,ID_MAYBE,ID_SILENT,ID_FOCUS,ID_BREAK,ID_LOOPS,ID_EFFECTS,ID_VOLUME,ID_ALARMTIME,ID_ALARMENABLE,ID_AUTOSTART,ID_SAVE,ID_POMODORO,ID_DICE,ID_ROLL,ID_COLLECTION,ID_EXIT,ID_COINLABEL,ID_OBSURL };

enum class Pose { Stand,Walk,Dash,Sit,Sleep,Fall,Climb,Joy,Dice,Dig,Petting,Look,Trip };
enum class Mode { Normal,Dragged,Falling,Climbing,Alert,Shopping,AngryHome,BlockedHome,ObsRest,Paused };
enum class ObjectKind { Coin,Item,Showcase,Cave };

struct ItemDef { const wchar_t* id; const wchar_t* name; const wchar_t* reaction; int category; int atlasIndex; };
static const ItemDef ITEMS[]={
 {L"aqua_ribbon",L"水色のリボン",L"我のリボン、似合う？",0,0},{L"salt_crystal",L"岩塩結晶の飾り",L"きらきら。洞窟の色だぞ、ますた。",0,1},{L"star_brooch",L"星のブローチ",L"我、ちょっとえらそう。",0,2},{L"tiny_bell",L"小さな鈴",L"鳴らさず見せるだけ。えらい。",0,3},{L"flower",L"花飾り",L"我、花まで似合ってしまう。",0,4},
 {L"cookie",L"クッキー",L"さくさく。ますたにも一口……ない。",1,0},{L"pudding",L"プリン",L"ぷるぷるは正義。",1,1},{L"donut",L"ドーナツ",L"穴のぶんだけカロリーが少ない……たぶん",1,2},{L"cupcake",L"カップケーキ",L"上から食べるか、下から食べるか。",1,3},{L"candy",L"キャンディ",L"あまい。もう一個ほしい。",1,4},
 {L"cat_teaser",L"猫じゃらし",L"我は猫では……ちょ、もう一回。",2,0},{L"yarn",L"毛糸玉",L"ほどくのは得意。戻すのは知らない。",2,1},{L"bell_ball",L"鈴ボール",L"ころころ……待てー！",2,2},{L"feather",L"羽根のおもちゃ",L"ふわふわが逃げる。",2,3},{L"plush",L"小さなぬいぐるみ",L"我がぬいを抱く。入れ子だな。",2,4}
};

struct Surface { HWND hwnd{}; RECT r{}; bool taskbar{}; };
struct WorldObject { HWND hwnd{}; ObjectKind kind{}; PngFrame frame; double x{},y{},vy{}; Clock::time_point expiry{}; int itemIndex{-1}; bool dragged{}; POINT dragOffset{}; };

static std::wstring Join(const std::wstring&a,const std::wstring&b){return a+L"\\"+b;}
static long long UnixNow(){return std::chrono::duration_cast<std::chrono::seconds>(std::chrono::system_clock::now().time_since_epoch()).count();}
static int Clamp(int x,int a,int b){return std::max(a,std::min(b,x));}
static bool ClassStarts(HWND h,const wchar_t* prefix){wchar_t c[256]{};GetClassNameW(h,c,255);return _wcsnicmp(c,prefix,wcslen(prefix))==0;}
static RECT MonitorRect(POINT p,bool work){HMONITOR m=MonitorFromPoint(p,MONITOR_DEFAULTTONEAREST);MONITORINFO i{sizeof(i)};GetMonitorInfoW(m,&i);return work?i.rcWork:i.rcMonitor;}
static RECT PrimaryWork(){POINT p{};MONITORINFO i{sizeof(i)};GetMonitorInfoW(MonitorFromPoint(p,MONITOR_DEFAULTTOPRIMARY),&i);return i.rcWork;}
static std::wstring ProcessPath(HWND h){DWORD pid{};GetWindowThreadProcessId(h,&pid);HANDLE p=OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION,FALSE,pid);if(!p)return{};std::vector<wchar_t>b(32768);DWORD n=(DWORD)b.size();BOOL ok=QueryFullProcessImageNameW(p,0,b.data(),&n);CloseHandle(p);return ok?std::wstring(b.data(),n):L"";}
static std::wstring Lower(std::wstring s){std::transform(s.begin(),s.end(),s.begin(),towlower);return s;}
static bool IsIgnored(HWND h){return ClassStarts(h,L"Fences");}
static bool IsShell(HWND h){return ClassStarts(h,L"Progman")||ClassStarts(h,L"WorkerW")||ClassStarts(h,L"Shell_TrayWnd")||ClassStarts(h,L"Shell_SecondaryTrayWnd");}
static bool IsCloaked(HWND h){DWORD v=0;return SUCCEEDED(DwmGetWindowAttribute(h,DWMWA_CLOAKED,&v,sizeof(v)))&&v;}
static RECT Bounds(HWND h){RECT r{};if(FAILED(DwmGetWindowAttribute(h,DWMWA_EXTENDED_FRAME_BOUNDS,&r,sizeof(r))))GetWindowRect(h,&r);return r;}
static bool RectContains(const RECT&r,POINT p){return p.x>=r.left&&p.x<r.right&&p.y>=r.top&&p.y<r.bottom;}
static bool DesktopListBlankAt(HWND h,POINT p){IAccessible* list=nullptr;if(FAILED(AccessibleObjectFromWindow(h,(DWORD)OBJID_CLIENT,IID_IAccessible,(void**)&list))||!list)return false;VARIANT hit{};VariantInit(&hit);HRESULT hr=list->accHitTest(p.x,p.y,&hit);bool blank=false;if(SUCCEEDED(hr)){if(hit.vt==VT_EMPTY)blank=true;else if(hit.vt==VT_I4&&hit.lVal==CHILDID_SELF)blank=true;else if(hit.vt==VT_DISPATCH&&hit.pdispVal){IAccessible* child=nullptr;if(SUCCEEDED(hit.pdispVal->QueryInterface(IID_IAccessible,(void**)&child))&&child){VARIANT self{};self.vt=VT_I4;self.lVal=CHILDID_SELF;VARIANT role{};VariantInit(&role);if(SUCCEEDED(child->get_accRole(self,&role))&&role.vt==VT_I4)blank=role.lVal==(LONG)ROLE_SYSTEM_LIST||role.lVal==(LONG)ROLE_SYSTEM_PANE||role.lVal==(LONG)ROLE_SYSTEM_WINDOW;VariantClear(&role);child->Release();}}}VariantClear(&hit);list->Release();return blank;}
static bool IsGamePath(const std::wstring& p){std::wstring s=Lower(p);if(s.find(L"\\steamapps\\common\\wallpaper_engine\\")!=s.npos||s.find(L"\\steamapps\\common\\lossless scaling\\")!=s.npos||s.find(L"\\steamapps\\common\\steamvr\\")!=s.npos)return false;return s.find(L"\\steamapps\\common\\")!=s.npos||s.find(L"\\epic games\\")!=s.npos||s.find(L"\\gog games\\")!=s.npos||s.find(L"\\xboxgames\\")!=s.npos;}
static bool ValidAlarmTime(const std::wstring& s){auto digit=[](wchar_t c){return c>=L'0'&&c<=L'9';};if(s.size()!=5||!digit(s[0])||!digit(s[1])||s[2]!=L':'||!digit(s[3])||!digit(s[4]))return false;int hour=(s[0]-L'0')*10+(s[1]-L'0'),minute=(s[3]-L'0')*10+(s[4]-L'0');return hour<24&&minute<60;}
static void PlayEffect(int volume){volume=Clamp(volume,0,100);std::thread([volume](){constexpr int rate=22050,samples=5512;std::vector<BYTE> data(samples);double amp=volume*1.1;for(int i=0;i<samples;++i){double hz=i<samples/2?740.0:988.0;data[i]=(BYTE)Clamp((int)(128+std::sin(6.283185307*hz*i/rate)*amp),0,255);}WAVEFORMATEX fmt{WAVE_FORMAT_PCM,1,rate,rate,1,8,0};HWAVEOUT out{};if(waveOutOpen(&out,WAVE_MAPPER,&fmt,0,0,CALLBACK_NULL)!=MMSYSERR_NOERROR)return;WAVEHDR hdr{};hdr.lpData=(LPSTR)data.data();hdr.dwBufferLength=(DWORD)data.size();waveOutPrepareHeader(out,&hdr,sizeof(hdr));waveOutWrite(out,&hdr,sizeof(hdr));while(!(hdr.dwFlags&WHDR_DONE))Sleep(10);waveOutUnprepareHeader(out,&hdr,sizeof(hdr));waveOutClose(out);}).detach();}

class App {
public:
    int run(HINSTANCE instance);
    LRESULT petProc(HWND,UINT,WPARAM,LPARAM);
    LRESULT objectProc(HWND,UINT,WPARAM,LPARAM);
    LRESULT settingsProc(HWND,UINT,WPARAM,LPARAM);
    void onTick();
private:
    HINSTANCE instance_{}; HWND pet_{},bubble_{},settingsWindow_{}; HHOOK mouseHook_{}; NOTIFYICONDATAW tray_{};
    std::wstring root_,dataDir_,charDir_; Settings settings_; Profile profile_; CharacterDef character_; ImageLoader images_; ObsServer obs_;
    PngFrame petFrame_; std::vector<PngFrame> animation_; std::vector<WorldObject> objects_; std::vector<Surface> surfaces_;
    std::mt19937 rng_{std::random_device{}()};
    Pose pose_{Pose::Stand}; Mode mode_{Mode::Normal},pausedMode_{Mode::Normal}; int frameIndex_{}, direction_{1},frameDirection_{1}; double x_{},y_{},vx_{},vy_{},alertBaseY_{},bubbleX_{},bubbleY_{},bubbleVx_{},bubbleVy_{}; int petSize_{180};
    Clock::time_point lastTick_{Clock::now()},nextAction_{Clock::now()},nextFrame_{Clock::now()},bubbleUntil_{},lastTerrainScan_{},blockedCheck_{},obsCheck_{},lastPoke_{},pauseStarted_{},obsPauseStarted_{};
    POINT dragOffset_{},lastMouse_{},pressPoint_{}; Clock::time_point lastDragMove_{},pressTime_{}; std::vector<Clock::time_point> pokes_; bool petting_{},pettingMoved_{},obsActive_{},blocked_{},shutdown_{},hourlyDone_{},phantomClimb_{},shopOpenedSettings_{},sessionLocked_{},suspended_{},bubbleThrown_{}; int lastHour_{-1},pendingShowcase_{-1};
    bool pomodoro_{},pomodoroBreak_{};int pomodoroRound_{};Clock::time_point pomodoroDue_{};
    int targetSurface_{-1}; double targetX_{};
    static App* self_; static LRESULT CALLBACK PetThunk(HWND,UINT,WPARAM,LPARAM); static LRESULT CALLBACK ObjectThunk(HWND,UINT,WPARAM,LPARAM); static LRESULT CALLBACK SettingsThunk(HWND,UINT,WPARAM,LPARAM); static LRESULT CALLBACK MouseHook(int,WPARAM,LPARAM);
    bool registerClasses(); void createPet(); void showSettings(); void layoutSettings(); void readSettingsControls(); void readActivity(); void saveAll(); void setAutoStart(bool);
    void setPose(Pose,bool loop=true); void loadPoseFrame(); void loadAnimation(const std::wstring&,int,int,int); void presentPet(); void applyDirection(); void movePet(double,double); RECT currentWork()const;
    void scanTerrain(); bool supported(double px,double bottom,int* surface=nullptr)const; void selectWindowTarget(); void beginFall(double impulse=0); void enterHome(bool angry); void leaveHome(); void handleBlocked();
    void showBubble(const std::wstring&,bool alert=false); void positionBubble(); void throwBubble(); void updateBubble(double); void hideBubble(); void poke(); void beginDrag(POINT); void dragMove(POINT); void endDrag(POINT); void summonRandomItem(POINT); void spawnCoin(); void spawnObject(ObjectKind,int,POINT); void updateObjects(double); void collect(size_t); void shopping(); void cleanupShoppingWindow(); void showPendingPurchase();
    void randomAction(); void scheduleAction(double minSec,double maxSec); void scheduleCoin(); void scheduleSpeech(); void checkClock(); void playAlert(); void dismissAlert(); void startPomodoro(); void stopPomodoro();
    bool desktopBlankAt(POINT)const; void onDesktopCall(POINT); bool anyBlockedScreen(RECT* which=nullptr,bool* isGame=nullptr,bool* isFullscreen=nullptr); void updateObs(); void updateTray(); void pauseSystem(); void resumeSystem(); void shiftSchedules(Clock::duration); void consumeMutedAlarm();
};
App* App::self_=nullptr;

LRESULT CALLBACK App::PetThunk(HWND h,UINT m,WPARAM w,LPARAM l){return self_?self_->petProc(h,m,w,l):DefWindowProcW(h,m,w,l);}
LRESULT CALLBACK App::ObjectThunk(HWND h,UINT m,WPARAM w,LPARAM l){return self_?self_->objectProc(h,m,w,l):DefWindowProcW(h,m,w,l);}
LRESULT CALLBACK App::SettingsThunk(HWND h,UINT m,WPARAM w,LPARAM l){return self_?self_->settingsProc(h,m,w,l):DefWindowProcW(h,m,w,l);}

bool App::registerClasses(){WNDCLASSEXW c{sizeof(c)};c.hInstance=instance_;c.hCursor=LoadCursor(nullptr,IDC_HAND);c.hIcon=LoadIcon(instance_,MAKEINTRESOURCE(IDI_APP));c.lpfnWndProc=PetThunk;c.lpszClassName=L"DesktopChibiFriend.Native.Pet";if(!RegisterClassExW(&c))return false;c.lpszClassName=L"DesktopChibiFriend.Native.Bubble";if(!RegisterClassExW(&c))return false;c.lpfnWndProc=ObjectThunk;c.lpszClassName=L"DesktopChibiFriend.Native.Object";if(!RegisterClassExW(&c))return false;c.lpfnWndProc=SettingsThunk;c.hCursor=LoadCursor(nullptr,IDC_ARROW);c.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);c.lpszClassName=L"DesktopChibiFriend.Native.Settings";return RegisterClassExW(&c)!=0;}

int App::run(HINSTANCE instance){instance_=instance;self_=this;HANDLE mutex=CreateMutexW(nullptr,TRUE,L"DesktopChibiFriend.SingleInstance.v1");if(!mutex||GetLastError()==ERROR_ALREADY_EXISTS){if(mutex)CloseHandle(mutex);MessageBoxW(nullptr,L"デスクトップちびフレンドは、すでに起きています。",L"ちび堕ふる",MB_OK|MB_ICONINFORMATION);return 0;}HRESULT com=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);if(FAILED(com)){ReleaseMutex(mutex);CloseHandle(mutex);MessageBoxW(nullptr,L"画面の初期化に失敗しました。",L"ちび堕ふる",MB_ICONERROR);return 1;}InitCommonControls();root_=ExecutableDirectory();LogLine(root_,L"v0.4.1 startup begin");dataDir_=Join(root_,L"data");CreateDirectoryW(dataDir_.c_str(),nullptr);charDir_=Join(Join(root_,L"characters"),L"chibidaful");LoadSettings(Join(dataDir_,L"settings.json"),settings_);LoadProfile(Join(dataDir_,L"profile.json"),profile_);EnsureInitialItems(profile_);LoadCharacter(Join(charDir_,L"character.json"),character_);petSize_=Clamp(settings_.desktopPetSize,96,420);if(!images_.initialize()||!registerClasses()){LogLine(root_,L"initialization failed: "+std::to_wstring(GetLastError()));MessageBoxW(nullptr,L"画像または画面の初期化に失敗しました。",L"ちび堕ふる",MB_ICONERROR);images_.shutdown();CoUninitialize();ReleaseMutex(mutex);CloseHandle(mutex);return 1;}createPet();if(!pet_){LogLine(root_,L"pet window creation failed: "+std::to_wstring(GetLastError()));images_.shutdown();CoUninitialize();ReleaseMutex(mutex);CloseHandle(mutex);return 2;}LogLine(root_,L"pet window created");
#ifdef DESKTOP_CHIBI_TEST_THROW
    showBubble(L"吹き出し投げ試験");throwBubble();
#endif
    tray_.cbSize=sizeof(tray_);tray_.hWnd=pet_;tray_.uID=1;tray_.uFlags=NIF_MESSAGE|NIF_ICON|NIF_TIP;tray_.uCallbackMessage=WM_TRAY;tray_.hIcon=LoadIcon(instance_,MAKEINTRESOURCE(IDI_APP));wcscpy_s(tray_.szTip,L"デスクトップちびフレンド v0.4.1");Shell_NotifyIconW(NIM_ADD,&tray_);setAutoStart(settings_.autoStart);mouseHook_=SetWindowsHookExW(WH_MOUSE_LL,MouseHook,instance_,0);if(!mouseHook_)LogLine(root_,L"mouse hook failed: "+std::to_wstring(GetLastError()));WTSRegisterSessionNotification(pet_,NOTIFY_FOR_THIS_SESSION);SetTimer(pet_,TIMER_TICK,33,nullptr);scheduleAction(2,5);updateObs();MSG msg{};while(GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}shutdown_=true;LogLine(root_,L"shutdown begin");KillTimer(pet_,TIMER_TICK);WTSUnRegisterSessionNotification(pet_);if(mouseHook_)UnhookWindowsHookEx(mouseHook_);obs_.stop();Shell_NotifyIconW(NIM_DELETE,&tray_);saveAll();images_.shutdown();CoUninitialize();ReleaseMutex(mutex);CloseHandle(mutex);return 0;}

void App::createPet(){RECT work=PrimaryWork();bool valid=false;if(profile_.lastX>-100000&&profile_.lastY>-100000){POINT saved{(LONG)(profile_.lastX+petSize_/2),(LONG)(profile_.lastY+petSize_/2)};std::pair<POINT,bool*> check{saved,&valid};EnumDisplayMonitors(nullptr,nullptr,[](HMONITOR m,HDC,LPRECT,LPARAM p)->BOOL{auto pair=(std::pair<POINT,bool*>*)p;MONITORINFO i{sizeof(i)};GetMonitorInfoW(m,&i);if(RectContains(i.rcMonitor,pair->first))*pair->second=true;return TRUE;},(LPARAM)&check);}x_=valid?profile_.lastX:work.left+80;y_=valid?profile_.lastY:work.bottom-petSize_;pet_=CreateWindowExW(WS_EX_LAYERED|WS_EX_TOOLWINDOW|WS_EX_TOPMOST|WS_EX_NOACTIVATE,L"DesktopChibiFriend.Native.Pet",L"ちび堕ふる",WS_POPUP,(int)x_,(int)y_,petSize_,petSize_,nullptr,nullptr,instance_,nullptr);setPose(Pose::Stand);ShowWindow(pet_,SW_SHOWNOACTIVATE);}

RECT App::currentWork()const{POINT p{(LONG)(x_+petSize_/2),(LONG)(y_+petSize_/2)};return MonitorRect(p,true);}void App::movePet(double nx,double ny){x_=nx;y_=ny;presentPet();}
void App::presentPet(){if(!petFrame_.bitmap)return;applyDirection();PngFrame* f=&petFrame_;if(!animation_.empty())f=&animation_[frameIndex_%animation_.size()];POINT p{(LONG)std::lround(x_),(LONG)std::lround(y_)};PresentLayered(pet_,*f,p);SetWindowPos(pet_,HWND_TOPMOST,p.x,p.y,f->width,f->height,SWP_NOACTIVATE|SWP_SHOWWINDOW);positionBubble();}
void App::applyDirection(){if(direction_==frameDirection_)return;MirrorFrame(petFrame_);for(auto&f:animation_)MirrorFrame(f);frameDirection_=direction_;}

void App::loadAnimation(const std::wstring& file,int cols,int rows,int row){animation_.clear();for(int i=0;i<cols;++i){PngFrame f;if(images_.loadCell(Join(charDir_,file),cols,rows,row*cols+i,petSize_,f))animation_.push_back(std::move(f));}frameIndex_=0;nextFrame_=Clock::now()+std::chrono::milliseconds(160);}
void App::loadPoseFrame(){animation_.clear();frameDirection_=1;int index=0;switch(pose_){case Pose::Walk:index=1;break;case Pose::Dash:index=2;break;case Pose::Sit:index=3;break;case Pose::Sleep:index=4;break;case Pose::Fall:index=5;break;case Pose::Climb:index=6;break;case Pose::Joy:index=7;break;case Pose::Dice:index=8;break;default:index=0;}
    if(pose_==Pose::Sit)loadAnimation(character_.sitWalk,4,2,0);else if(pose_==Pose::Walk)loadAnimation(character_.sitWalk,4,2,1);else if(pose_==Pose::Sleep)loadAnimation(character_.sleepLookTrip,4,3,0);else if(pose_==Pose::Climb)loadAnimation(character_.petClimb,4,2,1);else if(pose_==Pose::Petting)loadAnimation(character_.petClimb,4,2,0);else if(pose_==Pose::Look)loadAnimation(character_.sleepLookTrip,4,3,1);else if(pose_==Pose::Trip)loadAnimation(character_.sleepLookTrip,4,3,2);else if(pose_==Pose::Dig)loadAnimation(character_.dig,4,1,0);else images_.loadCell(Join(charDir_,character_.sprite),3,3,index,petSize_,petFrame_);EmptyWorkingSet(GetCurrentProcess());presentPet();}
void App::setPose(Pose p,bool){if(pose_==p&&!animation_.empty())return;pose_=p;loadPoseFrame();}

LRESULT App::petProc(HWND h,UINT m,WPARAM w,LPARAM l){switch(m){
case WM_TIMER:if(w==TIMER_TICK)onTick();return 0;
case WM_LBUTTONDOWN:{if(h==bubble_){hideBubble();return 0;}POINT p{GET_X_LPARAM(l),GET_Y_LPARAM(l)};if(mode_==Mode::Alert){dismissAlert();return 0;}POINT s{};GetCursorPos(&s);pressPoint_=s;pressTime_=Clock::now();if(p.y<petSize_*48/100){petting_=true;pettingMoved_=false;SetCapture(h);}else beginDrag(s);return 0;}
case WM_MOUSEMOVE:if(GetCapture()==h){POINT s{};GetCursorPos(&s);if(mode_==Mode::Dragged)dragMove(s);else if(petting_&&abs(s.x-pressPoint_.x)>5){pettingMoved_=true;setPose(Pose::Petting);}}return 0;
case WM_LBUTTONUP:if(h==bubble_){hideBubble();return 0;}if(GetCapture()==h){ReleaseCapture();POINT s{};GetCursorPos(&s);if(mode_==Mode::Dragged){if(abs(s.x-pressPoint_.x)<=5&&abs(s.y-pressPoint_.y)<=5){mode_=Mode::Normal;vx_=vy_=0;poke();}else endDrag(s);}else if(petting_){petting_=false;if(pettingMoved_){showBubble(L"わーい！");setPose(Pose::Joy);scheduleAction(1,2);}else poke();}}else poke();return 0;
case WM_RBUTTONUP:showSettings();return 0;
case WM_CONTEXTMENU:return 0;
case WM_TRAY:if(l==WM_LBUTTONUP||l==WM_RBUTTONUP)showSettings();return 0;
case WM_DESKTOP_CALL:{POINT p{GET_X_LPARAM(l),GET_Y_LPARAM(l)};onDesktopCall(p);return 0;}
case WM_DISPLAYCHANGE:{RECT r=currentWork();x_=std::clamp(x_,(double)r.left,(double)(r.right-petSize_));y_=std::clamp(y_,(double)r.top,(double)(r.bottom-petSize_));scanTerrain();presentPet();return 0;}
case WM_WTSSESSION_CHANGE:if(w==WTS_SESSION_LOCK){sessionLocked_=true;pauseSystem();ShowWindow(pet_,SW_HIDE);hideBubble();for(auto&o:objects_)ShowWindow(o.hwnd,SW_HIDE);}else if(w==WTS_SESSION_UNLOCK){sessionLocked_=false;if(!suspended_)resumeSystem();}return 0;
case WM_POWERBROADCAST:if(w==PBT_APMSUSPEND){suspended_=true;pauseSystem();}else if(w==PBT_APMRESUMEAUTOMATIC){suspended_=false;if(!sessionLocked_)resumeSystem();}return TRUE;
case WM_PAINT:if(h==bubble_){PAINTSTRUCT ps{};HDC dc=BeginPaint(h,&ps);RECT r{};GetClientRect(h,&r);HBRUSH fill=CreateSolidBrush(RGB(225,247,252));HPEN pen=CreatePen(PS_SOLID,2,RGB(62,181,211));HGDIOBJ ob=SelectObject(dc,fill),op=SelectObject(dc,pen);RoundRect(dc,1,1,r.right-1,r.bottom-1,18,18);SelectObject(dc,ob);SelectObject(dc,op);DeleteObject(fill);DeleteObject(pen);HFONT font=(HFONT)SendMessageW(h,WM_GETFONT,0,0);HGDIOBJ oldFont=font?SelectObject(dc,font):nullptr;SetBkMode(dc,TRANSPARENT);SetTextColor(dc,RGB(27,63,77));wchar_t text[1024]{};GetWindowTextW(h,text,1023);DrawTextW(dc,text,-1,&r,DT_CENTER|DT_VCENTER|DT_SINGLELINE|DT_END_ELLIPSIS);if(oldFont)SelectObject(dc,oldFont);EndPaint(h,&ps);return 0;}break;
case WM_QUERYENDSESSION:saveAll();return TRUE;
case WM_ENDSESSION:if(w)PostQuitMessage(0);return 0;
case WM_DESTROY:if(h==pet_)PostQuitMessage(0);return 0;}
return DefWindowProcW(h,m,w,l);}

LRESULT CALLBACK App::MouseHook(int code,WPARAM w,LPARAM l){static ULONGLONG lastRight=0,lastLeft=0;static POINT lastPoint{};static int leftCount=0;static bool lastRightBlank=false,swallowRightUp=false;auto summon=[&](POINT p){PostMessageW(self_->pet_,WM_DESKTOP_CALL,0,MAKELPARAM(p.x,p.y));lastRight=0;lastRightBlank=false;};if(code>=0&&self_&&!self_->shutdown_){auto* d=(MSLLHOOKSTRUCT*)l;if(w==WM_RBUTTONDOWN){ULONGLONG now=GetTickCount64();int dx=abs(d->pt.x-lastPoint.x),dy=abs(d->pt.y-lastPoint.y);if(lastRightBlank&&now-lastRight<=GetDoubleClickTime()&&dx<=GetSystemMetrics(SM_CXDOUBLECLK)&&dy<=GetSystemMetrics(SM_CYDOUBLECLK)){summon(d->pt);swallowRightUp=true;return 1;}}else if(w==WM_RBUTTONUP){if(swallowRightUp){swallowRightUp=false;return 1;}ULONGLONG now=GetTickCount64();int dx=abs(d->pt.x-lastPoint.x),dy=abs(d->pt.y-lastPoint.y);if(lastRightBlank&&now-lastRight<=GetDoubleClickTime()&&dx<=GetSystemMetrics(SM_CXDOUBLECLK)&&dy<=GetSystemMetrics(SM_CYDOUBLECLK)){summon(d->pt);return 1;}lastRight=now;lastPoint=d->pt;lastRightBlank=self_->desktopBlankAt(d->pt);}else if(w==WM_LBUTTONUP&&(self_->mode_==Mode::AngryHome||self_->mode_==Mode::BlockedHome)&&self_->desktopBlankAt(d->pt)){ULONGLONG now=GetTickCount64();if(now-lastLeft<=GetDoubleClickTime())leftCount++;else leftCount=1;lastLeft=now;if(leftCount>=3){PostMessageW(self_->pet_,WM_DESKTOP_CALL,0,MAKELPARAM(d->pt.x,d->pt.y));leftCount=0;}}}return CallNextHookEx(nullptr,code,w,l);}

bool App::desktopBlankAt(POINT p)const{HWND h=WindowFromPoint(p);if(!h)return true;HWND root=GetAncestor(h,GA_ROOT);if(IsIgnored(h)||(root&&IsIgnored(root)))return true;wchar_t cls[128]{};GetClassNameW(h,cls,127);if(_wcsicmp(cls,L"SysListView32")==0)return DesktopListBlankAt(h,p);return _wcsicmp(cls,L"Progman")==0||_wcsicmp(cls,L"WorkerW")==0||_wcsicmp(cls,L"SHELLDLL_DefView")==0;}

void App::onDesktopCall(POINT p){if(mode_==Mode::AngryHome||mode_==Mode::BlockedHome){leaveHome();showBubble(L"ますた、なに？");return;}summonRandomItem(p);}

void App::beginDrag(POINT p){mode_=Mode::Dragged;dragOffset_={(LONG)(p.x-x_),(LONG)(p.y-y_)};lastMouse_=p;lastDragMove_=Clock::now();vx_=vy_=0;SetCapture(pet_);}
void App::dragMove(POINT p){auto now=Clock::now();double dt=std::max(.005,std::chrono::duration<double>(now-lastDragMove_).count());vx_=(p.x-lastMouse_.x)/dt;vy_=(p.y-lastMouse_.y)/dt;lastMouse_=p;lastDragMove_=now;movePet(p.x-dragOffset_.x,p.y-dragOffset_.y);}
void App::endDrag(POINT){mode_=Mode::Falling;vx_=std::clamp(vx_,-1800.0,1800.0);vy_=std::clamp(vy_,-1400.0,1400.0);setPose(Pose::Fall);}

void App::poke(){auto now=Clock::now();pokes_.erase(std::remove_if(pokes_.begin(),pokes_.end(),[&](auto t){return now-t>std::chrono::minutes(5);}),pokes_.end());pokes_.push_back(now);if(pokes_.size()>=10){showBubble(L"むすーっ。ますた、つんつんしすぎ。",true);enterHome(true);pokes_.clear();return;}if(pokes_.size()>=7)showBubble(L"いたい。もうやだ。");else if(pokes_.size()>=4)showBubble(L"むすーっ。");else{static const wchar_t* s[]={L"ますた、なに？",L"びくっ。",L"いたい。",L"我はここ。"};showBubble(s[rng_()%std::size(s)]);}setPose(Pose::Joy);scheduleAction(1,3);}

void App::showBubble(const std::wstring& text,bool alert){hideBubble();bubbleThrown_=false;int width=std::min(520,std::max(150,40+(int)text.size()*18)),height=64;bubbleUntil_=Clock::now()+std::chrono::seconds(std::max<size_t>(3,(text.size()+1)/2));bubble_=CreateWindowExW(WS_EX_TOOLWINDOW|WS_EX_TOPMOST|WS_EX_NOACTIVATE|WS_EX_LAYERED,L"DesktopChibiFriend.Native.Bubble",text.c_str(),WS_POPUP,0,0,width,height,pet_,nullptr,instance_,nullptr);SetLayeredWindowAttributes(bubble_,0,248,LWA_ALPHA);HFONT font=CreateFontW(18,0,0,0,FW_NORMAL,FALSE,FALSE,FALSE,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,CLEARTYPE_QUALITY,DEFAULT_PITCH,L"Yu Gothic UI");SendMessageW(bubble_,WM_SETFONT,(WPARAM)font,TRUE);positionBubble();ShowWindow(bubble_,SW_SHOWNOACTIVATE);if(alert){mode_=Mode::Alert;SetWindowPos(pet_,HWND_TOPMOST,0,0,0,0,SWP_NOMOVE|SWP_NOSIZE|SWP_NOACTIVATE);}}
void App::positionBubble(){if(!bubble_)return;RECT br{};GetWindowRect(bubble_,&br);int width=br.right-br.left,height=br.bottom-br.top;if(bubbleThrown_){SetWindowPos(bubble_,HWND_TOPMOST,(int)std::lround(bubbleX_),(int)std::lround(bubbleY_),width,height,SWP_NOACTIVATE|SWP_SHOWWINDOW);return;}POINT center{(LONG)(x_+petSize_/2),(LONG)(y_+petSize_/2)};RECT area=MonitorRect(center,true);int bx=(int)x_+petSize_/2-width/2,by=(int)y_-height-5;if(by<area.top)by=(int)y_+petSize_+5;bx=Clamp(bx,area.left,std::max(area.left,area.right-width));by=Clamp(by,area.top,std::max(area.top,area.bottom-height));SetWindowPos(bubble_,HWND_TOPMOST,bx,by,width,height,SWP_NOACTIVATE|SWP_SHOWWINDOW);}
void App::throwBubble(){if(!bubble_||mode_==Mode::Alert)return;RECT r{};GetWindowRect(bubble_,&r);bubbleX_=r.left;bubbleY_=r.top;bubbleVx_=direction_*(260+(int)(rng_()%161));bubbleVy_=-300-(int)(rng_()%121);bubbleThrown_=true;}
void App::updateBubble(double dt){if(!bubble_||!bubbleThrown_)return;RECT r{};GetWindowRect(bubble_,&r);int width=r.right-r.left,height=r.bottom-r.top;bubbleVy_=std::min(850.0,bubbleVy_+720*dt);bubbleX_+=bubbleVx_*dt;bubbleY_+=bubbleVy_*dt;POINT center{(LONG)(bubbleX_+width/2),(LONG)(bubbleY_+height/2)};RECT area=MonitorRect(center,false);if(bubbleX_>area.right+width||bubbleX_+width<area.left-width||bubbleY_>area.bottom+height){hideBubble();return;}SetWindowPos(bubble_,HWND_TOPMOST,(int)std::lround(bubbleX_),(int)std::lround(bubbleY_),width,height,SWP_NOACTIVATE|SWP_SHOWWINDOW);}
void App::hideBubble(){bubbleThrown_=false;if(bubble_){HFONT f=(HFONT)SendMessageW(bubble_,WM_GETFONT,0,0);DestroyWindow(bubble_);if(f)DeleteObject(f);bubble_=nullptr;}}
void App::dismissAlert(){hideBubble();y_=alertBaseY_;mode_=Mode::Normal;setPose(Pose::Stand);scheduleAction(2,4);}
void App::shiftSchedules(Clock::duration delta){if(delta<=Clock::duration::zero())return;nextAction_+=delta;nextFrame_+=delta;if(bubbleUntil_!=Clock::time_point{})bubbleUntil_+=delta;if(pomodoro_)pomodoroDue_+=delta;for(auto&o:objects_)if(o.expiry!=Clock::time_point::max())o.expiry+=delta;long long seconds=std::chrono::duration_cast<std::chrono::seconds>(delta).count();if(profile_.nextCoinUnix>0)profile_.nextCoinUnix+=seconds;if(profile_.nextSpeechUnix>0)profile_.nextSpeechUnix+=seconds;}
void App::pauseSystem(){if(mode_==Mode::Paused)return;pausedMode_=mode_;if(pausedMode_==Mode::Dragged){pausedMode_=Mode::Falling;vy_=0;vx_=0;}if(GetCapture()==pet_)ReleaseCapture();petting_=false;pauseStarted_=Clock::now();mode_=Mode::Paused;}
void App::resumeSystem(){if(mode_!=Mode::Paused)return;auto now=Clock::now();if(pausedMode_!=Mode::ObsRest)shiftSchedules(now-pauseStarted_);mode_=pausedMode_;lastTick_=now;lastTerrainScan_={};blockedCheck_={};obsCheck_={};if(mode_!=Mode::AngryHome&&mode_!=Mode::BlockedHome&&mode_!=Mode::ObsRest){ShowWindow(pet_,SW_SHOWNOACTIVATE);for(auto&o:objects_)ShowWindow(o.hwnd,SW_SHOWNOACTIVATE);presentPet();if(mode_==Mode::Alert)showBubble(L"おわり！！",true);}}

LRESULT App::objectProc(HWND h,UINT m,WPARAM w,LPARAM l){auto it=std::find_if(objects_.begin(),objects_.end(),[&](const WorldObject&o){return o.hwnd==h;});if(it==objects_.end())return DefWindowProcW(h,m,w,l);switch(m){case WM_NCHITTEST:return HTCLIENT;case WM_LBUTTONDOWN:{POINT p{};GetCursorPos(&p);it->dragged=true;it->dragOffset={(LONG)(p.x-it->x),(LONG)(p.y-it->y)};SetCapture(h);return 0;}case WM_MOUSEMOVE:if(it->dragged){POINT p{};GetCursorPos(&p);it->x=p.x-it->dragOffset.x;it->y=p.y-it->dragOffset.y;POINT q{(LONG)it->x,(LONG)it->y};PresentLayered(h,it->frame,q);}return 0;case WM_LBUTTONUP:if(it->dragged){it->dragged=false;ReleaseCapture();it->vy=0;}return 0;}return DefWindowProcW(h,m,w,l);}

void App::spawnObject(ObjectKind kind,int item,POINT p){WorldObject o;o.kind=kind;o.itemIndex=item;o.x=p.x;o.y=p.y;o.vy=0;o.expiry=kind==ObjectKind::Showcase?Clock::now()+std::chrono::seconds(5):kind==ObjectKind::Item?Clock::time_point::max():Clock::now()+std::chrono::hours(1);int size=kind==ObjectKind::Coin?54:(kind==ObjectKind::Item||kind==ObjectKind::Showcase)?96:180;std::wstring file;int cols=1,index=0;if(kind==ObjectKind::Coin)file=Join(charDir_,character_.coin);else if(kind==ObjectKind::Item||kind==ObjectKind::Showcase){const ItemDef&d=ITEMS[item];file=Join(charDir_,d.category==0?character_.accessory:d.category==1?character_.sweet:character_.toy);cols=5;index=d.atlasIndex;}bool ok=kind==ObjectKind::Cave?CreateCaveFrame(size,o.frame):images_.loadCell(file,cols,1,index,size,o.frame);if(!ok)return;o.hwnd=CreateWindowExW(WS_EX_LAYERED|WS_EX_TOOLWINDOW|WS_EX_TOPMOST|WS_EX_NOACTIVATE,L"DesktopChibiFriend.Native.Object",L"",WS_POPUP,p.x,p.y,size,size,nullptr,nullptr,instance_,nullptr);objects_.push_back(std::move(o));auto& back=objects_.back();PresentLayered(back.hwnd,back.frame,p);ShowWindow(back.hwnd,SW_SHOWNOACTIVATE);}
void App::spawnCoin(){RECT w=currentWork();std::uniform_int_distribution<int>d(w.left+30,std::max(w.left+31,w.right-85));spawnObject(ObjectKind::Coin,-1,{d(rng_),w.top-60});scheduleCoin();}
void App::summonRandomItem(POINT p){for(size_t i=0;i<objects_.size();){if(objects_[i].kind==ObjectKind::Item){DestroyWindow(objects_[i].hwnd);objects_.erase(objects_.begin()+i);}else++i;}if(profile_.unlocked.empty())EnsureInitialItems(profile_);std::wstring id=profile_.unlocked[rng_()%profile_.unlocked.size()];int idx=0;for(int i=0;i<(int)std::size(ITEMS);++i)if(id==ITEMS[i].id){idx=i;break;}spawnObject(ObjectKind::Item,idx,{p.x-48,p.y-48});targetX_=p.x-petSize_/2;direction_=targetX_>x_?1:-1;vx_=direction_*420;mode_=Mode::Normal;setPose(Pose::Dash);nextAction_=Clock::now()+std::chrono::seconds(12);}
void App::collect(size_t i){if(i>=objects_.size())return;auto o=objects_[i].kind;int item=objects_[i].itemIndex;DestroyWindow(objects_[i].hwnd);objects_.erase(objects_.begin()+i);if(o==ObjectKind::Coin){profile_.coins++;showBubble(L"コイン！ うれしい。");setPose(Pose::Joy);saveAll();}else if(o==ObjectKind::Item&&item>=0){profile_.counts[ITEMS[item].id]++;showBubble(ITEMS[item].reaction);setPose(item>=5&&item<10?Pose::Sit:Pose::Joy);saveAll();}}

void App::scanTerrain(){HWND oldTarget=nullptr;if(targetSurface_>=0&&targetSurface_<(int)surfaces_.size())oldTarget=surfaces_[targetSurface_].hwnd;surfaces_.clear();struct Ctx{App*a;std::vector<RECT> blockers;};Ctx ctx{this,{}};EnumWindows([](HWND h,LPARAM p)->BOOL{auto&ctx=*(Ctx*)p;auto*a=ctx.a;if(!IsWindowVisible(h)||IsIconic(h)||IsCloaked(h)||IsShell(h)||IsIgnored(h))return TRUE;bool own=h==a->pet_||h==a->settingsWindow_||ClassStarts(h,L"DesktopChibiFriend.Native.");RECT r=Bounds(h);if(r.right<=r.left||r.bottom<=r.top)return TRUE;if(own)return TRUE;LONG_PTR ex=GetWindowLongPtrW(h,GWL_EXSTYLE);bool eligible=!IsZoomed(h)&&!(ex&WS_EX_TOOLWINDOW)&&!(ex&WS_EX_NOACTIVATE)&&r.right-r.left>=140&&r.bottom-r.top>=80;bool exposed=false;if(eligible){int width=r.right-r.left;for(int i=1;i<=9&&!exposed;++i){POINT q{r.left+width*i/10,r.top+4};exposed=std::none_of(ctx.blockers.begin(),ctx.blockers.end(),[&](const RECT&b){return RectContains(b,q);});}}ctx.blockers.push_back(r);if(eligible&&exposed)a->surfaces_.push_back({h,r,false});return TRUE;},(LPARAM)&ctx);EnumDisplayMonitors(nullptr,nullptr,[](HMONITOR m,HDC,LPRECT,LPARAM p)->BOOL{MONITORINFO i{sizeof(i)};GetMonitorInfoW(m,&i);((App*)p)->surfaces_.push_back({nullptr,{i.rcWork.left,i.rcWork.bottom,i.rcWork.right,i.rcWork.bottom+4},true});return TRUE;},(LPARAM)this);if(oldTarget){auto it=std::find_if(surfaces_.begin(),surfaces_.end(),[&](const Surface&s){return s.hwnd==oldTarget;});targetSurface_=it==surfaces_.end()?-1:(int)std::distance(surfaces_.begin(),it);}lastTerrainScan_=Clock::now();}
bool App::supported(double px,double bottom,int*out)const{double best=9999;int bi=-1;for(int i=0;i<(int)surfaces_.size();++i){const RECT&r=surfaces_[i].r;if(px>=r.left+8&&px<=r.right-8){double d=std::abs(bottom-r.top);if(d<best&&d<18){best=d;bi=i;}}}if(out)*out=bi;return bi>=0;}
void App::selectWindowTarget(){if(surfaces_.empty())scanTerrain();POINT center{(LONG)(x_+petSize_/2),(LONG)(y_+petSize_/2)};double best=1e9;int bi=-1;double tx=0;for(int i=0;i<(int)surfaces_.size();++i){auto&s=surfaces_[i];if(s.taskbar)continue;double left=s.r.left-petSize_*.62,right=s.r.right-petSize_*.38;double dl=std::abs(center.x-left)+std::abs((y_+petSize_)-s.r.bottom)*.2,dr=std::abs(center.x-right)+std::abs((y_+petSize_)-s.r.bottom)*.2;if(dl<best){best=dl;bi=i;tx=left;}if(dr<best){best=dr;bi=i;tx=right;}}if(bi>=0){targetSurface_=bi;targetX_=tx;direction_=targetX_>x_?1:-1;vx_=direction_*150;setPose(Pose::Walk);}}
void App::beginFall(double impulse){mode_=Mode::Falling;vy_=impulse;setPose(Pose::Fall);targetSurface_=-1;}
void App::enterHome(bool angry){hideBubble();mode_=angry?Mode::AngryHome:Mode::BlockedHome;for(auto&o:objects_)ShowWindow(o.hwnd,SW_HIDE);spawnObject(ObjectKind::Cave,-1,{(LONG)(x_-35),(LONG)(y_+10)});direction_=-1;vx_=-260;setPose(Pose::Dash);nextAction_=Clock::now()+std::chrono::milliseconds(700);}
void App::leaveHome(){for(size_t i=0;i<objects_.size();){if(objects_[i].kind==ObjectKind::Cave){DestroyWindow(objects_[i].hwnd);objects_.erase(objects_.begin()+i);}else++i;}mode_=Mode::Falling;blocked_=false;RECT w=PrimaryWork();x_=w.left+20;y_=w.top-petSize_;vy_=120;vx_=0;for(auto&o:objects_)ShowWindow(o.hwnd,SW_SHOWNOACTIVATE);setPose(Pose::Fall);ShowWindow(pet_,SW_SHOWNOACTIVATE);presentPet();}

void App::updateObjects(double dt){auto now=Clock::now();for(size_t i=0;i<objects_.size();){auto&o=objects_[i];if(o.expiry<now){DestroyWindow(o.hwnd);objects_.erase(objects_.begin()+i);continue;}if(!o.dragged&&o.kind!=ObjectKind::Cave&&o.kind!=ObjectKind::Showcase){double oldBottom=o.y+o.frame.height;o.vy=std::min(900.0,o.vy+900*dt);o.y+=o.vy*dt;double center=o.x+o.frame.width/2.0,newBottom=o.y+o.frame.height;double landing=1e30;for(auto&s:surfaces_)if(center>=s.r.left&&center<=s.r.right&&oldBottom<=s.r.top+4&&newBottom>=s.r.top&&s.r.top<landing)landing=s.r.top;if(landing<1e20){o.y=landing-o.frame.height;o.vy=0;}else{RECT work=MonitorRect({(LONG)o.x,(LONG)o.y},true);double floor=work.bottom-o.frame.height;if(o.y>=floor){o.y=floor;o.vy=0;}}POINT p{(LONG)o.x,(LONG)o.y};PresentLayered(o.hwnd,o.frame,p);}
        RECT pr{(LONG)x_,(LONG)y_,(LONG)(x_+petSize_),(LONG)(y_+petSize_)};RECT orc{(LONG)o.x,(LONG)o.y,(LONG)(o.x+o.frame.width),(LONG)(o.y+o.frame.height)};RECT hit{};if((o.kind==ObjectKind::Coin||o.kind==ObjectKind::Item)&&mode_!=Mode::Dragged&&IntersectRect(&hit,&pr,&orc)){collect(i);continue;}++i;}}

void App::randomAction(){if(mode_!=Mode::Normal||obsActive_||blocked_)return;int roll=(int)(rng_()%100);if(roll<40){selectWindowTarget();scheduleAction(8,15);}else if(roll<52){vx_=((rng_()%2)!=0?1.0:-1.0)*(70+rng_()%60);direction_=vx_>0?1:-1;setPose(Pose::Walk);scheduleAction(3,7);}else if(roll<65){vx_=0;setPose(Pose::Sit);scheduleAction(5,12);}else if(roll<75){vx_=0;setPose(Pose::Sleep);scheduleAction(10,22);}else if(roll<80){vx_=0;setPose(Pose::Look);scheduleAction(3,5);}else if(roll<84){phantomClimb_=true;mode_=Mode::Climbing;targetSurface_=-2;vx_=0;setPose(Pose::Climb);scheduleAction(2,4);}else if(roll<91){vx_=0;setPose(Pose::Dig);scheduleAction(4,7);if(rng_()%100<6){profile_.coins++;showBubble(L"……あった！ コイン！");saveAll();}}else if(roll<96){vx_=((rng_()%2)!=0?1.0:-1.0)*420;direction_=vx_>0?1:-1;setPose(Pose::Dash);scheduleAction(2,4);}else if(roll<99){vx_=0;setPose(Pose::Trip);scheduleAction(2,3);}else{vx_=0;setPose(Pose::Sit);showBubble(L"♪　♪");scheduleAction(5,9);}if(settings_.activity==L"しずか")nextAction_+=std::chrono::seconds(5);else if(settings_.activity==L"にぎやか")nextAction_-=std::chrono::seconds(2);}
void App::scheduleAction(double a,double b){std::uniform_real_distribution<double>d(a,b);nextAction_=Clock::now()+std::chrono::milliseconds((int)(d(rng_)*1000));}
void App::scheduleCoin(){int lo=Clamp(settings_.coinMinMinutes,1,60),hi=Clamp(settings_.coinMaxMinutes,lo,60);std::uniform_int_distribution<int>d(lo*60,hi*60);profile_.nextCoinUnix=UnixNow()+d(rng_);saveAll();}
void App::scheduleSpeech(){int lo=std::max(1,settings_.speechMinMinutes),hi=std::max(lo,settings_.speechMaxMinutes);std::uniform_int_distribution<int>d(lo*60,hi*60);profile_.nextSpeechUnix=UnixNow()+d(rng_);saveAll();}
void App::shopping(){if(profile_.coins<10||mode_!=Mode::Normal||obsActive_||blocked_)return;std::vector<int> locked;for(int i=0;i<(int)std::size(ITEMS);++i)if(std::find(profile_.unlocked.begin(),profile_.unlocked.end(),ITEMS[i].id)==profile_.unlocked.end())locked.push_back(i);int idx=locked.empty()?(int)(rng_()%std::size(ITEMS)):locked[rng_()%locked.size()];profile_.coins-=5;if(std::find(profile_.unlocked.begin(),profile_.unlocked.end(),ITEMS[idx].id)==profile_.unlocked.end())profile_.unlocked.push_back(ITEMS[idx].id);profile_.counts[ITEMS[idx].id]++;pendingShowcase_=idx;shopOpenedSettings_=settingsWindow_==nullptr;if(shopOpenedSettings_){settingsWindow_=CreateWindowExW(WS_EX_TOOLWINDOW,L"DesktopChibiFriend.Native.Settings",L"デスクトップちびフレンド v0.4.1 お店",WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU,CW_USEDEFAULT,CW_USEDEFAULT,720,720,nullptr,nullptr,instance_,nullptr);RECT work=currentWork();SetWindowPos(settingsWindow_,HWND_TOP,work.right-740,work.top+20,720,720,SWP_NOACTIVATE);ShowWindow(settingsWindow_,SW_SHOWNOACTIVATE);}mode_=Mode::Shopping;setPose(Pose::Dash);vx_=direction_*350;showBubble(L"お店、行ってくる！");saveAll();nextAction_=Clock::now()+std::chrono::seconds(3);targetSurface_=-1;}
void App::cleanupShoppingWindow(){if(shopOpenedSettings_&&settingsWindow_){DestroyWindow(settingsWindow_);settingsWindow_=nullptr;}shopOpenedSettings_=false;targetSurface_=-1;}
void App::showPendingPurchase(){int idx=pendingShowcase_;pendingShowcase_=-1;if(idx>=0&&idx<(int)std::size(ITEMS)){showBubble(std::wstring(L"見て、ますた！　")+ITEMS[idx].name+L"！");setPose(Pose::Joy);POINT p{(LONG)(x_+petSize_*.68),(LONG)(y_+petSize_*.25)};spawnObject(ObjectKind::Showcase,idx,p);}if(profile_.coins>=10){targetSurface_=2000;nextAction_=Clock::now()+std::chrono::seconds(7);}else scheduleAction(4,8);}

bool App::anyBlockedScreen(RECT* which,bool* game,bool* fullscreen){HWND fg=GetForegroundWindow();if(!fg||fg==pet_||fg==settingsWindow_||IsIconic(fg)||IsIgnored(fg)||IsShell(fg))return false;RECT wr=Bounds(fg);HMONITOR mon=MonitorFromWindow(fg,MONITOR_DEFAULTTONEAREST);MONITORINFO mi{sizeof(mi)};GetMonitorInfoW(mon,&mi);bool full=!IsZoomed(fg)&&wr.left<=mi.rcMonitor.left+2&&wr.top<=mi.rcMonitor.top+2&&wr.right>=mi.rcMonitor.right-2&&wr.bottom>=mi.rcMonitor.bottom-2;bool g=IsGamePath(ProcessPath(fg));if(!full&&!g)return false;if(which)*which=mi.rcMonitor;if(game)*game=g;if(fullscreen)*fullscreen=full;return true;}
void App::handleBlocked(){RECT r{};bool game=false,full=false;bool now=anyBlockedScreen(&r,&game,&full);POINT center{(LONG)(x_+petSize_/2),(LONG)(y_+petSize_/2)};bool on=now&&RectContains(r,center);if(now){for(auto&o:objects_)if(RectContains(r,{(LONG)o.x,(LONG)o.y}))ShowWindow(o.hwnd,SW_HIDE);}else if(!obsActive_&&mode_!=Mode::AngryHome&&mode_!=Mode::BlockedHome){for(auto&o:objects_)ShowWindow(o.hwnd,SW_SHOWNOACTIVATE);}if(now&&full&&pomodoro_)stopPomodoro();if(on&&mode_!=Mode::Alert&&mode_!=Mode::AngryHome&&mode_!=Mode::BlockedHome){if(mode_==Mode::Shopping)cleanupShoppingWindow();std::vector<RECT> candidates;EnumDisplayMonitors(nullptr,nullptr,[](HMONITOR m,HDC,LPRECT,LPARAM p)->BOOL{MONITORINFO i{sizeof(i)};GetMonitorInfoW(m,&i);((std::vector<RECT>*)p)->push_back(i.rcWork);return TRUE;},(LPARAM)&candidates);auto it=std::find_if(candidates.begin(),candidates.end(),[&](RECT a){POINT c{(a.left+a.right)/2,(a.top+a.bottom)/2};return !RectContains(r,c);});if(it!=candidates.end()){x_=it->left+20;y_=it->top-petSize_;mode_=Mode::Falling;vy_=180;setPose(Pose::Fall);presentPet();showBubble(game?L"ゲーム中。あっちにいる。":L"全力で避難！！");}else enterHome(false);}blocked_=on;if(!now&&mode_==Mode::BlockedHome)leaveHome();}

void App::updateObs(){bool active=IsObsRunning();if(active==obsActive_)return;obsActive_=active;if(active){obsPauseStarted_=Clock::now();if(mode_==Mode::Shopping)cleanupShoppingWindow();if(obs_.start(settings_.obsPort,root_,settings_.obsPetSize,settings_.coinMinMinutes,settings_.coinMaxMinutes))settings_.obsPort=obs_.port();mode_=Mode::ObsRest;ShowWindow(pet_,SW_HIDE);hideBubble();for(auto&o:objects_)ShowWindow(o.hwnd,SW_HIDE);}else{obs_.stop();if(obsPauseStarted_!=Clock::time_point{}){shiftSchedules(Clock::now()-obsPauseStarted_);obsPauseStarted_={};}if(mode_==Mode::ObsRest){mode_=Mode::Falling;RECT w=PrimaryWork();x_=w.left+20;y_=w.top-petSize_;vy_=120;setPose(Pose::Fall);ShowWindow(pet_,SW_SHOWNOACTIVATE);for(auto&o:objects_)ShowWindow(o.hwnd,SW_SHOWNOACTIVATE);}}}

void App::playAlert(){if(settings_.effectsEnabled&&!obsActive_)PlayEffect(settings_.effectsVolume);RECT r{};bool game=false;if(anyBlockedScreen(&r,&game)){x_=r.left+(r.right-r.left-petSize_)/2;y_=r.top+24;}alertBaseY_=y_;mode_=Mode::Alert;vx_=0;setPose(Pose::Joy);ShowWindow(pet_,SW_SHOWNOACTIVATE);showBubble(L"おわり！！",true);}
void App::startPomodoro(){pomodoro_=true;pomodoroBreak_=false;pomodoroRound_=1;pomodoroDue_=Clock::now()+std::chrono::minutes(settings_.focusMinutes);showBubble(L"集中、はじめ！");}
void App::stopPomodoro(){pomodoro_=false;if(mode_==Mode::Alert)dismissAlert();showBubble(L"ポモドーロ終了。");}
void App::checkClock(){SYSTEMTIME t{};GetLocalTime(&t);if((int)t.wHour!=lastHour_&&t.wMinute==0){lastHour_=t.wHour;showBubble(std::to_wstring(t.wHour)+L"時だよ！");}if(settings_.alarmEnabled&&!settings_.alarmTime.empty()&&!obsActive_){wchar_t now[6]{};swprintf_s(now,L"%02u:%02u",t.wHour,t.wMinute);if(settings_.alarmTime==now){settings_.alarmEnabled=false;playAlert();saveAll();}}if(pomodoro_&&Clock::now()>=pomodoroDue_){playAlert();pomodoroBreak_=!pomodoroBreak_;if(!pomodoroBreak_&&++pomodoroRound_>settings_.pomodoroLoops){pomodoro_=false;}else pomodoroDue_=Clock::now()+std::chrono::minutes(pomodoroBreak_?settings_.breakMinutes:settings_.focusMinutes);}}
void App::consumeMutedAlarm(){if(!settings_.alarmEnabled||!ValidAlarmTime(settings_.alarmTime))return;SYSTEMTIME t{};GetLocalTime(&t);wchar_t now[6]{};swprintf_s(now,L"%02u:%02u",t.wHour,t.wMinute);if(settings_.alarmTime==now){settings_.alarmEnabled=false;saveAll();}}

void App::onTick(){auto now=Clock::now();double dt=std::min(.08,std::chrono::duration<double>(now-lastTick_).count());lastTick_=now;if(mode_==Mode::Paused)return;if(now-obsCheck_>std::chrono::seconds(2)){obsCheck_=now;updateObs();}if(obsActive_||mode_==Mode::ObsRest){consumeMutedAlarm();return;}if(now-lastTerrainScan_>std::chrono::seconds(2))scanTerrain();if(now-blockedCheck_>std::chrono::seconds(1)){blockedCheck_=now;handleBlocked();checkClock();}
    if(bubble_&&mode_!=Mode::Alert&&now>=bubbleUntil_)hideBubble();if(bubbleThrown_)updateBubble(dt);if(!animation_.empty()&&now>=nextFrame_){frameIndex_=(frameIndex_+1)%(int)animation_.size();int ms=pose_==Pose::Sleep?480:pose_==Pose::Sit?280:pose_==Pose::Petting?130:pose_==Pose::Look?550:pose_==Pose::Dig?180:140;nextFrame_=now+std::chrono::milliseconds(ms);presentPet();}
    if(mode_==Mode::AngryHome||mode_==Mode::BlockedHome){if(now>=nextAction_){ShowWindow(pet_,SW_HIDE);vx_=0;for(size_t i=0;i<objects_.size();){if(objects_[i].kind==ObjectKind::Cave){DestroyWindow(objects_[i].hwnd);objects_.erase(objects_.begin()+i);}else++i;}}else{x_+=vx_*dt;presentPet();}return;}
    if(mode_==Mode::Alert){double phase=std::chrono::duration<double>(now.time_since_epoch()).count()*11;y_=alertBaseY_-std::abs(std::sin(phase))*24;presentPet();return;}if(mode_==Mode::Dragged){updateObjects(dt);return;}
    if(mode_==Mode::Shopping&&now>=nextAction_){mode_=Mode::Normal;vx_=0;cleanupShoppingWindow();showPendingPurchase();}else if(mode_==Mode::Normal&&pendingShowcase_>=0)showPendingPurchase();
    if(mode_==Mode::Falling){double oldBottom=y_+petSize_;vy_=std::min(1300.0,vy_+1000*dt);x_+=vx_*dt;y_+=vy_*dt;double newBottom=y_+petSize_;int si=-1;double landing=1e30;if(vy_>=0){double center=x_+petSize_/2;for(int i=0;i<(int)surfaces_.size();++i){const RECT&r=surfaces_[i].r;if(center>=r.left+8&&center<=r.right-8&&oldBottom<=r.top+4&&newBottom>=r.top-4&&r.top<landing){landing=r.top;si=i;}}}if(si>=0){y_=landing-petSize_;vy_=0;vx_=0;mode_=Mode::Normal;setPose(Pose::Sit);scheduleAction(3,7);}RECT w=currentWork();if(y_>w.bottom+petSize_||x_>w.right+petSize_||x_+petSize_<w.left-petSize_){RECT p=PrimaryWork();x_=p.left+(p.right-p.left-petSize_)/2;y_=p.top-petSize_;vx_=0;vy_=180;}presentPet();updateObjects(dt);return;}
    if(mode_==Mode::Climbing){if(phantomClimb_){y_-=95*dt;if(now>=nextAction_){phantomClimb_=false;showBubble(L"壁、なかった。");beginFall(-40);}presentPet();updateObjects(dt);return;}if(targetSurface_<0||targetSurface_>=(int)surfaces_.size()){beginFall();return;}RECT r=surfaces_[targetSurface_].r;y_-=170*dt;vx_=0;if(y_+petSize_<=r.top+3){if(rng_()%2){y_=r.top-petSize_;x_=std::clamp(x_,(double)r.left,(double)(r.right-petSize_));mode_=Mode::Normal;setPose(Pose::Sit);scheduleAction(5,12);}else{showBubble(L"あっ。");beginFall(-80);}}presentPet();updateObjects(dt);return;}
    x_+=vx_*dt;if(vx_!=0)direction_=vx_>0?1:-1;if(targetSurface_>=0&&targetSurface_<(int)surfaces_.size()&&std::abs(x_-targetX_)<8){x_=targetX_;vx_=0;if(rng_()%4!=0){showBubble(L"わっ。");beginFall(-120);}else{mode_=Mode::Climbing;setPose(Pose::Climb);}}else if(mode_==Mode::Normal&&!supported(x_+petSize_/2,y_+petSize_)){beginFall(0);}RECT w=currentWork();if(x_<w.left-petSize_*.9||x_>w.right-petSize_*.1){std::vector<RECT> mons;EnumDisplayMonitors(nullptr,nullptr,[](HMONITOR m,HDC,LPRECT,LPARAM p)->BOOL{MONITORINFO i{sizeof(i)};GetMonitorInfoW(m,&i);((std::vector<RECT>*)p)->push_back(i.rcWork);return TRUE;},(LPARAM)&mons);RECT*dest=nullptr;for(auto&r:mons){if(direction_>0&&r.left>=w.right-2){dest=&r;break;}if(direction_<0&&r.right<=w.left+2)dest=&r;}if(dest){x_=direction_>0?dest->left-petSize_*.45:dest->right-petSize_*.55;y_=dest->top-petSize_;beginFall(120);}else{x_=std::clamp(x_,(double)w.left,(double)(w.right-petSize_));vx_=-vx_;direction_=-direction_;}}
    if(now>=nextAction_&&mode_==Mode::Normal){if(targetSurface_>=1000)shopping();else if(pose_==Pose::Dash&&rng_()%3==0){vx_=0;setPose(Pose::Trip);scheduleAction(2,3);}else randomAction();}
    if(profile_.nextCoinUnix<=0)scheduleCoin();if(UnixNow()>=profile_.nextCoinUnix&&!blocked_)spawnCoin();if(profile_.nextSpeechUnix<=0)scheduleSpeech();if(UnixNow()>=profile_.nextSpeechUnix&&!settings_.silentMode&&!blocked_){bool maybe=(int)(rng_()%100)<settings_.maybeFrequency;auto&list=maybe?character_.maybeSpeech:character_.speech;if(!list.empty()){showBubble(list[rng_()%list.size()]);if(rng_()%5==0)throwBubble();}scheduleSpeech();}if(profile_.coins>=10&&rng_()%1200==0)shopping();presentPet();updateObjects(dt);}

static HWND AddControl(HWND parent,const wchar_t* cls,const wchar_t* text,DWORD style,int x,int y,int w,int h,int id){HWND c=CreateWindowExW(0,cls,text,WS_CHILD|WS_VISIBLE|style,x,y,w,h,parent,(HMENU)(INT_PTR)id,GetModuleHandleW(nullptr),nullptr);SendMessageW(c,WM_SETFONT,(WPARAM)GetStockObject(DEFAULT_GUI_FONT),TRUE);return c;}
static void SetInt(HWND w,int id,int value){SetDlgItemInt(w,id,value,FALSE);}static int GetInt(HWND w,int id,int def){BOOL ok=FALSE;UINT v=GetDlgItemInt(w,id,&ok,FALSE);return ok?(int)v:def;}

void App::showSettings(){if(!settingsWindow_){settingsWindow_=CreateWindowExW(WS_EX_APPWINDOW,L"DesktopChibiFriend.Native.Settings",L"デスクトップちびフレンド v0.4.1 設定",WS_OVERLAPPED|WS_CAPTION|WS_SYSMENU|WS_MINIMIZEBOX,CW_USEDEFAULT,CW_USEDEFAULT,720,720,nullptr,nullptr,instance_,nullptr);}if(!GetDlgItem(settingsWindow_,ID_ACTIVITY)){AddControl(settingsWindow_,L"STATIC",L"活動量",0,24,635,100,24,0);HWND c=AddControl(settingsWindow_,L"COMBOBOX",L"",CBS_DROPDOWNLIST,120,631,120,120,ID_ACTIVITY);for(auto s:{L"しずか",L"ふつう",L"にぎやか"})SendMessageW(c,CB_ADDSTRING,0,(LPARAM)s);}int activity=settings_.activity==L"しずか"?0:settings_.activity==L"にぎやか"?2:1;SendDlgItemMessageW(settingsWindow_,ID_ACTIVITY,CB_SETCURSEL,activity,0);ShowWindow(settingsWindow_,SW_SHOW);SetForegroundWindow(settingsWindow_);}
void App::layoutSettings(){if(!settingsWindow_)return;SetInt(settingsWindow_,ID_SIZE,settings_.desktopPetSize);SetInt(settingsWindow_,ID_OBSSIZE,settings_.obsPetSize);SetInt(settingsWindow_,ID_COINMIN,settings_.coinMinMinutes);SetInt(settingsWindow_,ID_COINMAX,settings_.coinMaxMinutes);SetInt(settingsWindow_,ID_SPEECHMIN,settings_.speechMinMinutes);SetInt(settingsWindow_,ID_SPEECHMAX,settings_.speechMaxMinutes);SetInt(settingsWindow_,ID_MAYBE,settings_.maybeFrequency);SetInt(settingsWindow_,ID_FOCUS,settings_.focusMinutes);SetInt(settingsWindow_,ID_BREAK,settings_.breakMinutes);SetInt(settingsWindow_,ID_LOOPS,settings_.pomodoroLoops);SetInt(settingsWindow_,ID_VOLUME,settings_.effectsVolume);CheckDlgButton(settingsWindow_,ID_SILENT,settings_.silentMode?BST_CHECKED:BST_UNCHECKED);CheckDlgButton(settingsWindow_,ID_EFFECTS,settings_.effectsEnabled?BST_CHECKED:BST_UNCHECKED);CheckDlgButton(settingsWindow_,ID_ALARMENABLE,settings_.alarmEnabled?BST_CHECKED:BST_UNCHECKED);CheckDlgButton(settingsWindow_,ID_AUTOSTART,settings_.autoStart?BST_CHECKED:BST_UNCHECKED);SetDlgItemTextW(settingsWindow_,ID_ALARMTIME,settings_.alarmTime.c_str());SetDlgItemTextW(settingsWindow_,ID_COINLABEL,(L"コイン："+std::to_wstring(profile_.coins)+L"枚").c_str());SetDlgItemTextW(settingsWindow_,ID_OBSURL,(L"OBS URL: http://127.0.0.1:"+std::to_wstring(settings_.obsPort)+L"/").c_str());HWND list=GetDlgItem(settingsWindow_,ID_COLLECTION);SendMessageW(list,LB_RESETCONTENT,0,0);for(auto&i:ITEMS){int n=profile_.counts.count(i.id)?profile_.counts[i.id]:0;std::wstring line=n?std::wstring(L"● ")+i.name+L"　× "+std::to_wstring(n):std::wstring(L"？ 未収集");SendMessageW(list,LB_ADDSTRING,0,(LPARAM)line.c_str());}}

void App::readSettingsControls(){settings_.desktopPetSize=Clamp(GetInt(settingsWindow_,ID_SIZE,180),96,420);settings_.obsPetSize=Clamp(GetInt(settingsWindow_,ID_OBSSIZE,180),96,420);settings_.coinMinMinutes=Clamp(GetInt(settingsWindow_,ID_COINMIN,15),1,60);settings_.coinMaxMinutes=Clamp(GetInt(settingsWindow_,ID_COINMAX,30),settings_.coinMinMinutes,60);settings_.speechMinMinutes=Clamp(GetInt(settingsWindow_,ID_SPEECHMIN,8),1,240);settings_.speechMaxMinutes=Clamp(GetInt(settingsWindow_,ID_SPEECHMAX,15),settings_.speechMinMinutes,240);settings_.maybeFrequency=Clamp(GetInt(settingsWindow_,ID_MAYBE,30),0,100);settings_.focusMinutes=Clamp(GetInt(settingsWindow_,ID_FOCUS,25),1,240);settings_.breakMinutes=Clamp(GetInt(settingsWindow_,ID_BREAK,5),1,120);settings_.pomodoroLoops=Clamp(GetInt(settingsWindow_,ID_LOOPS,4),1,20);settings_.effectsVolume=Clamp(GetInt(settingsWindow_,ID_VOLUME,65),0,100);settings_.silentMode=IsDlgButtonChecked(settingsWindow_,ID_SILENT)==BST_CHECKED;settings_.effectsEnabled=IsDlgButtonChecked(settingsWindow_,ID_EFFECTS)==BST_CHECKED;settings_.alarmEnabled=IsDlgButtonChecked(settingsWindow_,ID_ALARMENABLE)==BST_CHECKED;settings_.autoStart=IsDlgButtonChecked(settingsWindow_,ID_AUTOSTART)==BST_CHECKED;wchar_t b[32]{};GetDlgItemTextW(settingsWindow_,ID_ALARMTIME,b,31);settings_.alarmTime=b;bool alarmInvalid=settings_.alarmEnabled&&!ValidAlarmTime(settings_.alarmTime);if(alarmInvalid)settings_.alarmEnabled=false;if(settings_.desktopPetSize!=petSize_){petSize_=settings_.desktopPetSize;loadPoseFrame();}setAutoStart(settings_.autoStart);saveAll();layoutSettings();showBubble(alarmInvalid?L"アラームはHH:MMで入れて。":L"設定した。");}
void App::readActivity(){int n=(int)SendDlgItemMessageW(settingsWindow_,ID_ACTIVITY,CB_GETCURSEL,0,0);settings_.activity=n==0?L"しずか":n==2?L"にぎやか":L"ふつう";}

LRESULT App::settingsProc(HWND h,UINT m,WPARAM w,LPARAM l){switch(m){case WM_CREATE:{settingsWindow_=h;int x=24,y=18;AddControl(h,L"STATIC",L"表示",SS_LEFT,x,y,300,24,0);y+=30;AddControl(h,L"STATIC",L"デスクトップサイズ",0,x,y,150,24,0);AddControl(h,L"EDIT",L"",WS_BORDER|ES_NUMBER,x+160,y-3,72,25,ID_SIZE);AddControl(h,L"STATIC",L"px",0,x+238,y,30,24,0);y+=34;AddControl(h,L"STATIC",L"OBSサイズ",0,x,y,150,24,0);AddControl(h,L"EDIT",L"",WS_BORDER|ES_NUMBER,x+160,y-3,72,25,ID_OBSSIZE);y+=42;AddControl(h,L"STATIC",L"コイン出現（分） 最短 / 最長",0,x,y,240,24,0);y+=27;AddControl(h,L"EDIT",L"",WS_BORDER|ES_NUMBER,x,y,70,25,ID_COINMIN);AddControl(h,L"STATIC",L"～",SS_CENTER,x+75,y,25,24,0);AddControl(h,L"EDIT",L"",WS_BORDER|ES_NUMBER,x+105,y,70,25,ID_COINMAX);y+=40;AddControl(h,L"STATIC",L"おしゃべり（分） 最短 / 最長",0,x,y,240,24,0);y+=27;AddControl(h,L"EDIT",L"",WS_BORDER|ES_NUMBER,x,y,70,25,ID_SPEECHMIN);AddControl(h,L"STATIC",L"～",SS_CENTER,x+75,y,25,24,0);AddControl(h,L"EDIT",L"",WS_BORDER|ES_NUMBER,x+105,y,70,25,ID_SPEECHMAX);y+=35;AddControl(h,L"STATIC",L"『…たぶん』頻度 %",0,x,y,150,24,0);AddControl(h,L"EDIT",L"",WS_BORDER|ES_NUMBER,x+160,y-3,72,25,ID_MAYBE);y+=34;AddControl(h,L"BUTTON",L"無言にする",BS_AUTOCHECKBOX,x,y,150,24,ID_SILENT);y+=42;AddControl(h,L"STATIC",L"ポモドーロ　集中 / 休憩 / 回数",0,x,y,260,24,0);y+=27;AddControl(h,L"EDIT",L"",WS_BORDER|ES_NUMBER,x,y,58,25,ID_FOCUS);AddControl(h,L"EDIT",L"",WS_BORDER|ES_NUMBER,x+68,y,58,25,ID_BREAK);AddControl(h,L"EDIT",L"",WS_BORDER|ES_NUMBER,x+136,y,58,25,ID_LOOPS);y+=37;AddControl(h,L"BUTTON",L"自動開始 / 終了",0,x,y,170,30,ID_POMODORO);y+=48;AddControl(h,L"STATIC",L"効果音の音量 %",0,x,y,150,24,0);AddControl(h,L"EDIT",L"",WS_BORDER|ES_NUMBER,x+160,y-3,72,25,ID_VOLUME);y+=30;AddControl(h,L"BUTTON",L"効果音を鳴らす",BS_AUTOCHECKBOX,x,y,170,24,ID_EFFECTS);y+=38;AddControl(h,L"STATIC",L"アラーム（HH:MM）",0,x,y,150,24,0);AddControl(h,L"EDIT",L"",WS_BORDER,x+160,y-3,72,25,ID_ALARMTIME);y+=30;AddControl(h,L"BUTTON",L"1回だけ有効",BS_AUTOCHECKBOX,x,y,150,24,ID_ALARMENABLE);y+=34;AddControl(h,L"BUTTON",L"Windows起動時に起こす",BS_AUTOCHECKBOX,x,y,210,24,ID_AUTOSTART);
        int rx=340,ry=18;AddControl(h,L"STATIC",L"所持品",0,rx,ry,180,24,0);AddControl(h,L"STATIC",L"",0,rx+180,ry,140,24,ID_COINLABEL);ry+=30;AddControl(h,L"LISTBOX",L"",WS_BORDER|WS_VSCROLL|LBS_NOINTEGRALHEIGHT,rx,ry,330,340,ID_COLLECTION);ry+=355;AddControl(h,L"STATIC",L"ダイス",0,rx,ry,80,24,0);HWND dice=AddControl(h,L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_VSCROLL,rx+70,ry-4,100,180,ID_DICE);for(auto s:{L"1d3",L"1d4",L"1d6",L"1d10",L"1d20",L"1d100"})SendMessageW(dice,CB_ADDSTRING,0,(LPARAM)s);SendMessageW(dice,CB_SETCURSEL,2,0);AddControl(h,L"BUTTON",L"振る",0,rx+180,ry-4,80,28,ID_ROLL);ry+=45;AddControl(h,L"STATIC",L"",0,rx,ry,330,44,ID_OBSURL);AddControl(h,L"BUTTON",L"設定を保存",BS_DEFPUSHBUTTON,rx,570,150,34,ID_SAVE);AddControl(h,L"BUTTON",L"アプリを終了",0,rx+165,570,150,34,ID_EXIT);layoutSettings();return 0;}
    case WM_COMMAND:{int id=LOWORD(w);if(id==ID_SAVE){readActivity();readSettingsControls();}else if(id==ID_POMODORO){readActivity();readSettingsControls();if(pomodoro_)stopPomodoro();else startPomodoro();}else if(id==ID_ROLL){int sel=(int)SendDlgItemMessageW(h,ID_DICE,CB_GETCURSEL,0,0);int sides[]={3,4,6,10,20,100};sel=Clamp(sel,0,5);int result=1+(int)(rng_()%sides[sel]);vx_=0;mode_=Mode::Normal;setPose(Pose::Dice);showBubble(L"1d"+std::to_wstring(sides[sel])+L" → "+std::to_wstring(result)+L"！");scheduleAction(4,5);}else if(id==ID_EXIT){if(MessageBoxW(h,L"ちび堕ふるを終了しますか？",L"アプリを終了",MB_YESNO|MB_ICONQUESTION)==IDYES)DestroyWindow(pet_);}return 0;}
    case WM_CLOSE:DestroyWindow(h);return 0;case WM_DESTROY:if(h==settingsWindow_)settingsWindow_=nullptr;return 0;}return DefWindowProcW(h,m,w,l);}

void App::saveAll(){profile_.lastX=x_;profile_.lastY=y_;SaveSettings(Join(dataDir_,L"settings.json"),settings_);SaveProfile(Join(dataDir_,L"profile.json"),profile_);}
void App::setAutoStart(bool enabled){HKEY key{};if(RegCreateKeyExW(HKEY_CURRENT_USER,L"Software\\Microsoft\\Windows\\CurrentVersion\\Run",0,nullptr,0,KEY_SET_VALUE,nullptr,&key,nullptr)!=ERROR_SUCCESS)return;if(enabled){std::wstring value=L"\""+Join(root_,L"DesktopChibiFriend.exe")+L"\"";RegSetValueExW(key,L"DesktopChibiFriend",0,REG_SZ,(BYTE*)value.c_str(),(DWORD)((value.size()+1)*sizeof(wchar_t)));}else RegDeleteValueW(key,L"DesktopChibiFriend");RegCloseKey(key);}
void App::updateTray(){}

int WINAPI wWinMain(HINSTANCE h,HINSTANCE,PWSTR,int){App app;return app.run(h);}
