#include <windows.h>
#include <iostream>
#include <filesystem>
#include <vector>
#include <string>
#include "image.h"
#include "storage.h"

struct Sheet { const wchar_t* name; int columns,rows; };
int wmain(int argc,wchar_t**argv){CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);ImageLoader images;if(!images.initialize()){std::wcerr<<L"WIC init failed\n";return 1;}std::wstring root=argc>1?argv[1]:ExecutableDirectory(),chars=root+L"\\characters\\chibidaful";Sheet sheets[]={{L"sprites-v5.png",3,3},{L"animations-sit-walk-v7.png",4,2},{L"animations-pet-climb-v6.png",4,2},{L"animations-sleep-look-trip-v6.png",4,3},{L"animations-dig-v3.png",4,1},{L"items-accessories-v3.png",5,1},{L"items-sweets-v3.png",5,1},{L"items-toys-v3.png",5,1},{L"coin-v2.png",1,1}};int failures=0,frames=0;for(auto&s:sheets){for(int i=0;i<s.columns*s.rows;++i){PngFrame f;if(!images.loadCell(chars+L"\\"+s.name,s.columns,s.rows,i,180,f)){std::wcerr<<L"LOAD FAIL "<<s.name<<L" #"<<i<<L"\n";failures++;continue;}auto*p=(DWORD*)f.pixels;int opaque=0,minx=180,miny=180,maxx=-1,maxy=-1;for(int y=0;y<180;++y)for(int x=0;x<180;++x)if((p[y*180+x]>>24)!=0){opaque++;minx=minx<x?minx:x;miny=miny<y?miny:y;maxx=maxx>x?maxx:x;maxy=maxy>y?maxy:y;}if(opaque<50){std::wcerr<<L"EMPTY "<<s.name<<L" #"<<i<<L"\n";failures++;}frames++;}std::wcout<<L"OK "<<s.name<<L" "<<s.columns*s.rows<<L" frames\n";}Settings st;Profile pr;std::wstring settingsPath=root+L"\\data\\settings.json",profilePath=root+L"\\data\\profile.json";bool hasSettings=std::filesystem::exists(settingsPath),hasProfile=std::filesystem::exists(profilePath),sl=false,pl=false,dataOk=false;if(!hasSettings&&!hasProfile){EnsureInitialItems(pr);dataOk=pr.unlocked.size()>=3;}else if(hasSettings&&hasProfile){sl=LoadSettings(settingsPath,st);pl=LoadProfile(profilePath,pr);EnsureInitialItems(pr);dataOk=sl&&pl&&pr.unlocked.size()>=3;}if(!dataOk){std::wcerr<<L"DATA FAIL\n";failures++;}const wchar_t* dataState=!hasSettings&&!hasProfile?L"CLEAN":sl&&pl?L"OK":L"FAIL";std::wcout<<L"Frames="<<frames<<L" Data="<<dataState<<L" Coins="<<pr.coins<<L" Items="<<pr.unlocked.size()<<L" Failures="<<failures<<L"\n";images.shutdown();CoUninitialize();return failures?2:0;}
